# Generated by Django 3.2.5 on 2024-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_remove_fasetorneo_jugadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetorneo',
            name='lista_partidos_alias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='lista_partidos_resultados_alias',
            field=models.TextField(default=''),
        ),
    ]
